name: Documentation Update
about: Suggest an update to the documentation

title: "[Documentation Update] "

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Documentation Update
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Location in Documentation
    validations:
      required: true
  - type: textarea
    id: suggested_changes
    attributes:
      label: Suggested Changes
    validations:
      required: true
  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information